// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6jPgcLGAOhMcVMzXXWm_27HPOVW2EST4',
    appId: '1:928521851239:web:bf3500d1887947e6d05fc2',
    messagingSenderId: '928521851239',
    projectId: 'bcv-tracker-6a452',
    authDomain: 'bcv-tracker-6a452.firebaseapp.com',
    storageBucket: 'bcv-tracker-6a452.firebasestorage.app',
    measurementId: 'G-D6C7C4734W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYVStJt02mw2cdfPC2NqF1OuhOu2j51Mw',
    appId: '1:928521851239:android:646d17abe717499fd05fc2',
    messagingSenderId: '928521851239',
    projectId: 'bcv-tracker-6a452',
    storageBucket: 'bcv-tracker-6a452.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8QbCjhYATqdUFU_HeBhVjESkGLi3XsJI',
    appId: '1:928521851239:ios:50110f5d9ed64737d05fc2',
    messagingSenderId: '928521851239',
    projectId: 'bcv-tracker-6a452',
    storageBucket: 'bcv-tracker-6a452.firebasestorage.app',
    iosBundleId: 'com.example.bcvTrackerApp',
  );
}
